import {
  FileImage,
  FileText,
  FileType,
  Mic,
  CheckSquare,
  Target,
  Image as ImageIcon,
  Layout,
  MessageCircle,
  Settings,
  GitMerge,
  FolderTree,
  FilePlus,
  Scissors,
  Crop,
  Lock,
  Layers,
  Minimize2,
  ScanText,
  PenTool,
  Plus,
  UserPlus,
  FolderPlus,
  UploadCloud,
  BellPlus,
  SunMoon,
  Timer,
  BookOpen,
  Video,
  Newspaper,
  Headphones,
  Network,
  RefreshCw,
} from "lucide-react";
import type { ComponentType } from "react";

export interface FerramentaApp {
  id: string;
  titulo: string;
  descricao: string;
  categoria: "conversor" | "ferramenta" | "modulo" | "acao";
  rota: string;
  icone: ComponentType<{ size?: number; className?: string }>;
  palavrasChave: string[];
}

export const LISTA_FERRAMENTAS_APP: FerramentaApp[] = [
  // --- FERRAMENTAS ILOVEPDF / PDF ---
  {
    id: "pdf_juntar",
    titulo: "Juntar e Mesclar PDFs (iLovePDF)",
    descricao: "Combine múltiplos arquivos PDF em um único documento organizado",
    categoria: "ferramenta",
    rota: "/pdf?aba=juntar",
    icone: FilePlus,
    palavrasChave: ["pdf", "juntar", "mesclar", "combinar", "unir", "ilovepdf", "documentos"],
  },
  {
    id: "pdf_dividir",
    titulo: "Dividir PDF / Extrair Páginas (iLovePDF)",
    descricao: "Separe páginas de um PDF ou escolha intervalos específicos para extrair",
    categoria: "ferramenta",
    rota: "/pdf?aba=dividir",
    icone: Scissors,
    palavrasChave: ["pdf", "dividir", "extrair", "separar", "páginas", "intervalo", "ilovepdf"],
  },
  {
    id: "pdf_comprimir",
    titulo: "Comprimir e Reduzir PDF (iLovePDF)",
    descricao: "Reduza o tamanho de arquivos PDF pesados sem perder qualidade visual",
    categoria: "ferramenta",
    rota: "/pdf?aba=comprimir",
    icone: Minimize2,
    palavrasChave: ["pdf", "comprimir", "reduzir", "tamanho", "peso", "otimizar", "ilovepdf"],
  },
  {
    id: "pdf_recortar",
    titulo: "Recortar Margens de PDF (iLovePDF)",
    descricao: "Ajuste e corte as margens em branco de páginas de um arquivo PDF",
    categoria: "ferramenta",
    rota: "/pdf?aba=recortar",
    icone: Crop,
    palavrasChave: ["pdf", "recortar", "margens", "cortar", "ajustar", "ilovepdf"],
  },
  {
    id: "pdf_desbloquear",
    titulo: "Desbloquear PDF (iLovePDF)",
    descricao: "Remova senhas e restrições de proteção contra cópia ou impressão",
    categoria: "ferramenta",
    rota: "/pdf?aba=desbloquear",
    icone: Lock,
    palavrasChave: ["pdf", "desbloquear", "senha", "proteger", "remover senha", "ilovepdf"],
  },
  {
    id: "pdf_organizar",
    titulo: "Organizar e Reordenar Páginas PDF",
    descricao: "Mude a ordem, gire e organize páginas de um documento PDF livremente",
    categoria: "ferramenta",
    rota: "/pdf?aba=organizar",
    icone: Layers,
    palavrasChave: ["pdf", "organizar", "reordenar", "ordenar", "mover páginas", "ilovepdf"],
  },
  {
    id: "pdf_ocr",
    titulo: "Reconhecimento OCR de PDF e Imagem",
    descricao: "Extraia texto pesquisável e legível de PDFs digitalizados e fotos",
    categoria: "ferramenta",
    rota: "/conversor?ferramenta=ocr",
    icone: ScanText,
    palavrasChave: ["pdf", "ocr", "texto", "reconhecer", "digitalizado", "extrair texto", "tesseract"],
  },

  // --- LOUSAS E EXCALIDRAW ---
  {
    id: "excalidraw_nova",
    titulo: "Nova Lousa / Canvas Excalidraw",
    descricao: "Abra um quadro em branco para desenhar, rascunhar e criar mapas mentais",
    categoria: "ferramenta",
    rota: "/lousas?nova=true",
    icone: PenTool,
    palavrasChave: ["lousa", "excalidraw", "desenho", "canvas", "novo", "esboço", "mapa mental", "diagrama"],
  },
  {
    id: "lousas",
    titulo: "Lousas Visuais (Excalidraw)",
    descricao: "Galeria de quadros Excalidraw, diagramas e mapas mentais salvos",
    categoria: "modulo",
    rota: "/lousas",
    icone: Layout,
    palavrasChave: ["lousa", "excalidraw", "canvas", "diagrama", "mapas mentais", "desenhos"],
  },

  // --- CONVERSÕES ---
  {
    id: "pdf_para_png",
    titulo: "PDF para PNG",
    descricao: "Extrai e converte cada página de um PDF em imagens PNG de alta resolução",
    categoria: "conversor",
    rota: "/conversor?ferramenta=pdf_para_png",
    icone: FileImage,
    palavrasChave: ["pdf", "png", "imagem", "extrair", "páginas", "converter"],
  },
  {
    id: "pdf_para_jpg",
    titulo: "PDF para JPG",
    descricao: "Converte páginas de PDF em arquivos de imagem JPG compactos",
    categoria: "conversor",
    rota: "/conversor?ferramenta=pdf_para_jpg",
    icone: FileImage,
    palavrasChave: ["pdf", "jpg", "jpeg", "imagem", "converter"],
  },
  {
    id: "img_para_pdf",
    titulo: "Imagens para PDF",
    descricao: "Junta uma ou mais imagens (PNG, JPG, WebP) em um único documento PDF",
    categoria: "conversor",
    rota: "/conversor?ferramenta=img_para_pdf",
    icone: FileText,
    palavrasChave: ["imagem", "pdf", "juntar", "compilar", "gerar pdf"],
  },
  {
    id: "img_para_webp",
    titulo: "Converter para WebP",
    descricao: "Otimize suas imagens para WebP com tamanho reduzido e alta qualidade",
    categoria: "conversor",
    rota: "/conversor?ferramenta=img_para_webp",
    icone: ImageIcon,
    palavrasChave: ["webp", "imagem", "otimizar", "comprimir", "converter"],
  },
  {
    id: "img_para_png",
    titulo: "Converter para PNG",
    descricao: "Transforme imagens JPG, WebP ou GIF em formato PNG transparente",
    categoria: "conversor",
    rota: "/conversor?ferramenta=img_para_png",
    icone: ImageIcon,
    palavrasChave: ["png", "imagem", "converter"],
  },
  {
    id: "img_para_jpg",
    titulo: "Converter para JPG",
    descricao: "Transforme imagens PNG ou WebP em formato JPG",
    categoria: "conversor",
    rota: "/conversor?ferramenta=img_para_jpg",
    icone: ImageIcon,
    palavrasChave: ["jpg", "jpeg", "imagem", "converter"],
  },
  {
    id: "pdf_para_epub",
    titulo: "Conversor: PDF para EPUB",
    descricao: "Extraia o texto de documentos PDF e monte um arquivo de livro digital EPUB",
    categoria: "conversor",
    rota: "/conversor?ferramenta=pdf_para_epub",
    icone: FileText,
    palavrasChave: ["pdf", "epub", "livro", "digital", "converter", "texto", "leitura"],
  },
  {
    id: "epub_trocar_capa",
    titulo: "Conversor: Trocar Capa de EPUB",
    descricao: "Substitua a imagem de capa de um livro digital EPUB existente",
    categoria: "conversor",
    rota: "/conversor?ferramenta=epub_trocar_capa",
    icone: FileImage,
    palavrasChave: ["epub", "capa", "trocar capa", "livro", "imagem", "substituir capa", "editar"],
  },
  {
    id: "texto_para_md",
    titulo: "Texto/HTML/JSON para Markdown",
    descricao: "Converte textos colados, arquivos TXT, HTML, JSON ou CSV em notas Markdown",
    categoria: "conversor",
    rota: "/conversor?ferramenta=texto_para_md",
    icone: FileType,
    palavrasChave: ["texto", "html", "json", "csv", "markdown", "md", "converter", "nota"],
  },

  // --- MÓDULOS E FERRAMENTAS DO KLAUS ---
  {
    id: "pesquisa_livros",
    titulo: "Pesquisar e Baixar Livros",
    descricao: "Busque e baixe livros e PDFs de domínio público/abertos de forma rápida e direta",
    categoria: "ferramenta",
    rota: "/livros",
    icone: BookOpen,
    palavrasChave: ["livros", "pesquisar livros", "pdf", "epub", "baixar", "gutenberg", "open library", "gutenberg", "biblioteca"],
  },
  {
    id: "contatos",
    titulo: "Árvore de Contatos & Pessoas",
    descricao: "Gerencie contatos, rede de relacionamentos, hierarquias (chefe/equipe) e propriedades editáveis",
    categoria: "modulo",
    rota: "/contatos",
    icone: FolderTree,
    palavrasChave: ["contatos", "árvore", "pessoas", "equipe", "chefe", "hierarquia", "rede", "relacionamentos", "csv"],
  },
  {
    id: "testador_hardware",
    titulo: "Diagnóstico de Hardware",
    descricao: "Verifique o feed de vídeo, grave um áudio de teste e monitore seus microfones",
    categoria: "ferramenta",
    rota: "/testador",
    icone: Video,
    palavrasChave: ["câmera", "microfone", "áudio", "vídeo", "hardware", "diagnóstico", "teste", "espelho", "camera", "som"],
  },
  {
    id: "transcritor",
    titulo: "Transcritor de Áudio & Voz",
    descricao: "Grave voz ou envie arquivos de áudio para transcrição e resumo com IA",
    categoria: "ferramenta",
    rota: "/transcritor",
    icone: Mic,
    palavrasChave: ["áudio", "gravador", "transcrição", "voz", "resumo", "ia"],
  },
  {
    id: "processos",
    titulo: "Construtor de Processos & Pipelines",
    descricao: "Crie funis de trabalho flexíveis, CRM, checklists por etapa e automações",
    categoria: "modulo",
    rota: "/processos",
    icone: GitMerge,
    palavrasChave: ["processo", "pipeline", "crm", "funil", "automação", "pipefy", "etapas"],
  },
  {
    id: "tarefas",
    titulo: "Quadro de Tarefas (Kanban)",
    descricao: "Gerencie tarefas, prazos, prioridades e cronômetro Pomodoro",
    categoria: "modulo",
    rota: "/tarefas",
    icone: CheckSquare,
    palavrasChave: ["tarefas", "kanban", "fazer", "pomodoro", "prazos"],
  },
  {
    id: "pdi",
    titulo: "Plano de Carreira & Metas (PDI)",
    descricao: "Acompanhe suas metas de carreira e entregas do PDI",
    categoria: "modulo",
    rota: "/pdi",
    icone: Target,
    palavrasChave: ["metas", "pdi", "entregas", "carreira", "desenvolvimento"],
  },
  {
    id: "referencias",
    titulo: "Referências Visuais (Pinterest)",
    descricao: "Galeria de imagens, inspirações visuais e upload de referências",
    categoria: "modulo",
    rota: "/referencias",
    icone: ImageIcon,
    palavrasChave: ["referências", "fotos", "galeria", "inspirações", "design", "imagens", "pinterest"],
  },
  {
    id: "chat_ia",
    titulo: "Assistente IA do Klaus",
    descricao: "Converse com a IA para buscar contexto, tirar dúvidas ou organizar ideias",
    categoria: "ferramenta",
    rota: "/chat",
    icone: MessageCircle,
    palavrasChave: ["chat", "ia", "gemini", "ajuda", "assistente"],
  },
  {
    id: "configuracoes",
    titulo: "Ajustes e Conexões",
    descricao: "Configure seus tokens do GitHub, chave do Gemini e preferências",
    categoria: "ferramenta",
    rota: "/config",
    icone: Settings,
    palavrasChave: ["ajustes", "configuração", "token", "github", "gemini", "senha"],
  },
  {
    id: "ferramentas_pdf",
    titulo: "Suíte de Ferramentas PDF (iLovePDF)",
    descricao: "Juntar, dividir, comprimir, recortar, desbloquear e organizar páginas de PDF",
    categoria: "ferramenta",
    rota: "/pdf",
    icone: FilePlus,
    palavrasChave: ["pdf", "ilovepdf", "mesclar", "dividir", "comprimir", "recortar", "desbloquear", "organizar"],
  },
  {
    id: "conversor",
    titulo: "Conversor Universal & Utilitários",
    descricao: "Conversões de imagem (PNG, JPG, WebP), OCR, Markdown e livros EPUB",
    categoria: "ferramenta",
    rota: "/conversor",
    icone: RefreshCw,
    palavrasChave: ["conversor", "converter", "imagem", "ocr", "texto", "epub", "markdown"],
  },
  {
    id: "sons",
    titulo: "Sons Ambiente & Foco",
    descricao: "Sons relaxantes de chuva, cafeteria, ruído branco e ondas para concentração",
    categoria: "ferramenta",
    rota: "/sons",
    icone: Headphones,
    palavrasChave: ["sons", "foco", "ruído branco", "chuva", "cafeteria", "áudio", "ambiente", "concentração", "música"],
  },
  {
    id: "noticias",
    titulo: "Radar de Notícias & Feed RSS",
    descricao: "Acompanhe novidades, tendências e feeds RSS em tempo real",
    categoria: "modulo",
    rota: "/noticias",
    icone: Newspaper,
    palavrasChave: ["notícias", "radar", "feed", "rss", "novidades", "artigos", "design"],
  },
  {
    id: "grafo",
    titulo: "Grafo Neural de Conhecimento",
    descricao: "Explore as conexões e relacionamentos visuais entre todas as suas notas e ideias",
    categoria: "modulo",
    rota: "/grafo",
    icone: Network,
    palavrasChave: ["grafo", "neural", "rede", "conexões", "mapa mental", "relacionamentos", "obsidian"],
  },

  // --- AÇÕES RÁPIDAS (QUICK ACTIONS) ---
  {
    id: "acao_nova_nota",
    titulo: "Criar Nova Nota",
    descricao: "Abra instantaneamente a tela de criação de nota em Markdown",
    categoria: "acao",
    rota: "/notas?nova=true",
    icone: Plus,
    palavrasChave: ["criar nota", "nova nota", "escrever nota", "adicionar nota", "nova"],
  },
  {
    id: "acao_nova_tarefa",
    titulo: "Criar Nova Tarefa",
    descricao: "Cadastre uma nova tarefa com prazo, prioridade e checklist",
    categoria: "acao",
    rota: "/tarefas?nova=true",
    icone: CheckSquare,
    palavrasChave: ["criar tarefa", "nova tarefa", "fazer", "adicionar tarefa", "pendencia"],
  },
  {
    id: "acao_novo_contato",
    titulo: "Adicionar Novo Contato",
    descricao: "Cadastre um novo contato na sua árvore de relacionamentos",
    categoria: "acao",
    rota: "/contatos?novo=true",
    icone: UserPlus,
    palavrasChave: ["criar contato", "novo contato", "adicionar pessoa", "equipe", "adicionar contato"],
  },
  {
    id: "acao_novo_processo",
    titulo: "Criar Novo Processo / Funil",
    descricao: "Crie um novo pipeline Kanban de processos ou CRM",
    categoria: "acao",
    rota: "/processos?novo=true",
    icone: FolderPlus,
    palavrasChave: ["criar processo", "novo processo", "novo funil", "novo pipeline", "crm"],
  },
  {
    id: "acao_nova_meta",
    titulo: "Criar Meta no PDI",
    descricao: "Cadastre uma nova meta profissional no seu Plano de Desenvolvimento",
    categoria: "acao",
    rota: "/pdi?nova_meta=true",
    icone: Target,
    palavrasChave: ["criar meta", "nova meta", "pdi", "carreira", "desenvolvimento"],
  },
  {
    id: "acao_upload_referencia",
    titulo: "Upload de Referência Visual",
    descricao: "Envie novas imagens e inspirações visuais para a sua galeria",
    categoria: "acao",
    rota: "/referencias?upload=true",
    icone: UploadCloud,
    palavrasChave: ["upload", "nova imagem", "enviar foto", "nova referencia", "inspiração"],
  },
  {
    id: "acao_novo_lembrete",
    titulo: "Criar Lembrete na Caixa de Entrada",
    descricao: "Cadastre um novo lembrete com notificação e data",
    categoria: "acao",
    rota: "/inbox?novo=true",
    icone: BellPlus,
    palavrasChave: ["criar lembrete", "novo lembrete", "inbox", "notificação", "alerta"],
  },
  {
    id: "acao_alternar_tema",
    titulo: "Alternar Tema Claro / Escuro",
    descricao: "Mude o tema visual do Klaus entre modo escuro (dark) e claro (light)",
    categoria: "acao",
    rota: "acao:alternar_tema",
    icone: SunMoon,
    palavrasChave: ["tema", "escuro", "claro", "dark mode", "light mode", "modo escuro", "modo claro", "aparencia"],
  },
  {
    id: "acao_iniciar_pomodoro",
    titulo: "Iniciar Cronômetro Pomodoro",
    descricao: "Abra o temporizador de foco Pomodoro para concentrar no trabalho",
    categoria: "acao",
    rota: "acao:iniciar_pomodoro",
    icone: Timer,
    palavrasChave: ["pomodoro", "cronometro", "temporizador", "foco", "timer"],
  },
];
