import {
  FileImage,
  FileText,
  FileType,
  Mic,
  CheckSquare,
  Target,
  Image as ImageIcon,
  Layout,
  MessageCircle,
  Settings,
  GitMerge,
  FolderTree,
  FilePlus,
  Scissors,
  Crop,
  Lock,
  Layers,
  Minimize2,
  ScanText,
  PenTool,
} from "lucide-react";
import type { ComponentType } from "react";

export interface FerramentaApp {
  id: string;
  titulo: string;
  descricao: string;
  categoria: "conversor" | "ferramenta" | "modulo";
  rota: string;
  icone: ComponentType<{ size?: number; className?: string }>;
  palavrasChave: string[];
}

export const LISTA_FERRAMENTAS_APP: FerramentaApp[] = [
  // --- FERRAMENTAS ILOVEPDF / PDF ---
  {
    id: "pdf_juntar",
    titulo: "Juntar e Mesclar PDFs (iLovePDF)",
    descricao: "Combine múltiplos arquivos PDF em um único documento organizado",
    categoria: "ferramenta",
    rota: "/pdf?aba=juntar",
    icone: FilePlus,
    palavrasChave: ["pdf", "juntar", "mesclar", "combinar", "unir", "ilovepdf", "documentos"],
  },
  {
    id: "pdf_dividir",
    titulo: "Dividir PDF / Extrair Páginas (iLovePDF)",
    descricao: "Separe páginas de um PDF ou escolha intervalos específicos para extrair",
    categoria: "ferramenta",
    rota: "/pdf?aba=dividir",
    icone: Scissors,
    palavrasChave: ["pdf", "dividir", "extrair", "separar", "páginas", "intervalo", "ilovepdf"],
  },
  {
    id: "pdf_comprimir",
    titulo: "Comprimir e Reduzir PDF (iLovePDF)",
    descricao: "Reduza o tamanho de arquivos PDF pesados sem perder qualidade visual",
    categoria: "ferramenta",
    rota: "/pdf?aba=comprimir",
    icone: Minimize2,
    palavrasChave: ["pdf", "comprimir", "reduzir", "tamanho", "peso", "otimizar", "ilovepdf"],
  },
  {
    id: "pdf_recortar",
    titulo: "Recortar Margens de PDF (iLovePDF)",
    descricao: "Ajuste e corte as margens em branco de páginas de um arquivo PDF",
    categoria: "ferramenta",
    rota: "/pdf?aba=recortar",
    icone: Crop,
    palavrasChave: ["pdf", "recortar", "margens", "cortar", "ajustar", "ilovepdf"],
  },
  {
    id: "pdf_desbloquear",
    titulo: "Desbloquear PDF (iLovePDF)",
    descricao: "Remova senhas e restrições de proteção contra cópia ou impressão",
    categoria: "ferramenta",
    rota: "/pdf?aba=desbloquear",
    icone: Lock,
    palavrasChave: ["pdf", "desbloquear", "senha", "proteger", "remover senha", "ilovepdf"],
  },
  {
    id: "pdf_organizar",
    titulo: "Organizar e Reordenar Páginas PDF",
    descricao: "Mude a ordem, gire e organize páginas de um documento PDF livremente",
    categoria: "ferramenta",
    rota: "/pdf?aba=organizar",
    icone: Layers,
    palavrasChave: ["pdf", "organizar", "reordenar", "ordenar", "mover páginas", "ilovepdf"],
  },
  {
    id: "pdf_ocr",
    titulo: "Reconhecimento OCR de PDF e Imagem",
    descricao: "Extraia texto pesquisável e legível de PDFs digitalizados e fotos",
    categoria: "ferramenta",
    rota: "/conversor?ferramenta=ocr",
    icone: ScanText,
    palavrasChave: ["pdf", "ocr", "texto", "reconhecer", "digitalizado", "extrair texto", "tesseract"],
  },

  // --- LOUSAS E EXCALIDRAW ---
  {
    id: "excalidraw_nova",
    titulo: "Nova Lousa / Canvas Excalidraw",
    descricao: "Abra um quadro em branco para desenhar, rascunhar e criar mapas mentais",
    categoria: "ferramenta",
    rota: "/lousas?nova=true",
    icone: PenTool,
    palavrasChave: ["lousa", "excalidraw", "desenho", "canvas", "novo", "esboço", "mapa mental", "diagrama"],
  },
  {
    id: "lousas",
    titulo: "Lousas Visuais (Excalidraw)",
    descricao: "Galeria de quadros Excalidraw, diagramas e mapas mentais salvos",
    categoria: "modulo",
    rota: "/lousas",
    icone: Layout,
    palavrasChave: ["lousa", "excalidraw", "canvas", "diagrama", "mapas mentais", "desenhos"],
  },

  // --- CONVERSÕES ---
  {
    id: "pdf_para_png",
    titulo: "PDF para PNG",
    descricao: "Extrai e converte cada página de um PDF em imagens PNG de alta resolução",
    categoria: "conversor",
    rota: "/conversor?ferramenta=pdf_para_png",
    icone: FileImage,
    palavrasChave: ["pdf", "png", "imagem", "extrair", "páginas", "converter"],
  },
  {
    id: "pdf_para_jpg",
    titulo: "PDF para JPG",
    descricao: "Converte páginas de PDF em arquivos de imagem JPG compactos",
    categoria: "conversor",
    rota: "/conversor?ferramenta=pdf_para_jpg",
    icone: FileImage,
    palavrasChave: ["pdf", "jpg", "jpeg", "imagem", "converter"],
  },
  {
    id: "img_para_pdf",
    titulo: "Imagens para PDF",
    descricao: "Junta uma ou mais imagens (PNG, JPG, WebP) em um único documento PDF",
    categoria: "conversor",
    rota: "/conversor?ferramenta=img_para_pdf",
    icone: FileText,
    palavrasChave: ["imagem", "pdf", "juntar", "compilar", "gerar pdf"],
  },
  {
    id: "img_para_webp",
    titulo: "Converter para WebP",
    descricao: "Otimize suas imagens para WebP com tamanho reduzido e alta qualidade",
    categoria: "conversor",
    rota: "/conversor?ferramenta=img_para_webp",
    icone: ImageIcon,
    palavrasChave: ["webp", "imagem", "otimizar", "comprimir", "converter"],
  },
  {
    id: "img_para_png",
    titulo: "Converter para PNG",
    descricao: "Transforme imagens JPG, WebP ou GIF em formato PNG transparente",
    categoria: "conversor",
    rota: "/conversor?ferramenta=img_para_png",
    icone: ImageIcon,
    palavrasChave: ["png", "imagem", "converter"],
  },
  {
    id: "img_para_jpg",
    titulo: "Converter para JPG",
    descricao: "Transforme imagens PNG ou WebP em formato JPG",
    categoria: "conversor",
    rota: "/conversor?ferramenta=img_para_jpg",
    icone: ImageIcon,
    palavrasChave: ["jpg", "jpeg", "imagem", "converter"],
  },
  {
    id: "texto_para_md",
    titulo: "Texto/HTML/JSON para Markdown",
    descricao: "Converte textos colados, arquivos TXT, HTML, JSON ou CSV em notas Markdown",
    categoria: "conversor",
    rota: "/conversor?ferramenta=texto_para_md",
    icone: FileType,
    palavrasChave: ["texto", "html", "json", "csv", "markdown", "md", "converter", "nota"],
  },

  // --- MÓDULOS E FERRAMENTAS DO KLAUS ---
  {
    id: "contatos",
    titulo: "Árvore de Contatos & Pessoas",
    descricao: "Gerencie contatos, rede de relacionamentos, hierarquias (chefe/equipe) e propriedades editáveis",
    categoria: "modulo",
    rota: "/contatos",
    icone: FolderTree,
    palavrasChave: ["contatos", "árvore", "pessoas", "equipe", "chefe", "hierarquia", "rede", "relacionamentos", "csv"],
  },
  {
    id: "transcritor",
    titulo: "Transcritor de Áudio & Voz",
    descricao: "Grave voz ou envie arquivos de áudio para transcrição e resumo com IA",
    categoria: "ferramenta",
    rota: "/transcritor",
    icone: Mic,
    palavrasChave: ["áudio", "gravador", "transcrição", "voz", "resumo", "ia"],
  },
  {
    id: "processos",
    titulo: "Construtor de Processos & Pipelines",
    descricao: "Crie funis de trabalho flexíveis, CRM, checklists por etapa e automações",
    categoria: "modulo",
    rota: "/processos",
    icone: GitMerge,
    palavrasChave: ["processo", "pipeline", "crm", "funil", "automação", "pipefy", "etapas"],
  },
  {
    id: "tarefas",
    titulo: "Quadro de Tarefas (Kanban)",
    descricao: "Gerencie tarefas, prazos, prioridades e cronômetro Pomodoro",
    categoria: "modulo",
    rota: "/tarefas",
    icone: CheckSquare,
    palavrasChave: ["tarefas", "kanban", "fazer", "pomodoro", "prazos"],
  },
  {
    id: "pdi",
    titulo: "Plano de Carreira & Metas (PDI)",
    descricao: "Acompanhe suas metas de carreira e entregas do PDI",
    categoria: "modulo",
    rota: "/pdi",
    icone: Target,
    palavrasChave: ["metas", "pdi", "entregas", "carreira", "desenvolvimento"],
  },
  {
    id: "referencias",
    titulo: "Referências Visuais (Pinterest)",
    descricao: "Galeria de imagens, inspirações visuais e upload de referências",
    categoria: "modulo",
    rota: "/referencias",
    icone: ImageIcon,
    palavrasChave: ["referências", "fotos", "galeria", "inspirações", "design", "imagens", "pinterest"],
  },
  {
    id: "chat_ia",
    titulo: "Assistente IA do Klaus",
    descricao: "Converse com a IA para buscar contexto, tirar dúvidas ou organizar ideias",
    categoria: "ferramenta",
    rota: "/chat",
    icone: MessageCircle,
    palavrasChave: ["chat", "ia", "gemini", "ajuda", "assistente"],
  },
  {
    id: "configuracoes",
    titulo: "Ajustes e Conexões",
    descricao: "Configure seus tokens do GitHub, chave do Gemini e preferências",
    categoria: "ferramenta",
    rota: "/config",
    icone: Settings,
    palavrasChave: ["ajustes", "configuração", "token", "github", "gemini", "senha"],
  },
];
